[package]
name = "glare"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
phf = { version = "0.8.0", features = ["macros"] }
tinytemplate = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"